/*
SOMETIMES OUR PROGRAM GETS BIGGER IN SIZE AND IT IS NOT POSSIBLE FOR A PROGRAM TO TRACK WHICH PIECE OF CODE IS DOING WHAT.
FUNCTION IS A WAY TO BREAK OUR CODE INTO CHUNKS THAT ARE POSSIBLE FOR A PROGRAMMER TO UNDERSTAND EASILY AND REUSE.

WHAT IS A FUNCTION?
=> A FUNCTION IS A BLOCK OF CODE WHICH PERFORMS A PARTICULAR TASK.
   IT CAN BE REUSED IN A PROGRAM ANY NUMBER OF TIMES.
----------------------------------------------------------------------------------------------------------------------------------------
*/
#include<stdio.h>
void display(); //=> FUNCTION PROTOTYPE

int main()
{
    display();  //=> FUNCTION CALL  
    return 0;
}

void display(){            //=> FUNCTION DEFINITION
    printf("Hello there!");
}

/*
 FUNCTION PROTOTYPE:- FUNCTION PROTOTYPE IS A WAY TO TELL THE COMPILER ABOUT THE FUNCTION WE ARE GOING TO DEFINE IN THE PROGRAM.
 VOID INDICATES THAT THE FUNCTION RETURNS NOTHHING.

 FUNCTION CALL:- FUNCTION CALL IS A WAY TO TELL THE COMPILER TO EXECUTE THE FUNCTION BODY AT THE TIME THE CALL IS MADE.
 NOTE THAT THE PROGRAM EXECUTION STARTS FROM THE MAIN FUNCTION IN THE SEQUENCE THE INSTRUCTIONS ARE WRITTEN.

 FUNCTION DEFINITION:- THIS PART CONTAINS THE EXACT SET OF INSTRUCTIONS WHICH ARE EXECUTED DURING THE FUNCTION CALL. 
 WHEN A FUNCTION IS CALLEDE FROM main(), THE MAIN FUNCTION FALL ASLEEP AND IS TEMPORARILY SUSPENDEED.
 DURING THIS TIME THE CONTROL GOES TO THE FUNCTION BEING CALLED.
 WHEN THE FUNCTION BODY IS DONE EXECUTING, main() RESUMES. 
*/
